# =============================================================================
# Упрощённый GitLab CI/CD Pipeline для тестирования
# =============================================================================

stages:
  - validate
  - plan

# Глобальные переменные
variables:
  TF_ENVIRONMENTS_PATH: "terraform/environments"

# Job для валидации
validate:
  stage: validate
  image:
    name: hashicorp/terraform:1.6
    entrypoint: [""]
  script:
    - echo "=== Валидация Terraform ==="
    - terraform version
    - |
      for ENV_DIR in ${TF_ENVIRONMENTS_PATH}/*/; do
        ENV_NAME=$(basename ${ENV_DIR})
        echo "--- Валидация ${ENV_NAME} ---"
        cd ${ENV_DIR}
        terraform init -backend=false
        terraform validate
        cd -
      done
    - echo "✓ Валидация завершена"
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"

# Job для plan
plan:
  stage: plan
  image:
    name: hashicorp/terraform:1.6
    entrypoint: [""]
  script:
    - echo "=== Terraform Plan ==="
    - |
      for ENV_DIR in ${TF_ENVIRONMENTS_PATH}/*/; do
        ENV_NAME=$(basename ${ENV_DIR})
        echo "--- Plan ${ENV_NAME} ---"
        cd ${ENV_DIR}
        terraform init -backend=false
        terraform plan -input=false || true
        cd -
      done
    - echo "✓ Plan завершён"
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"
