stages:
  - smoke_test
  - terraform_lint
  - terraform_apply
  - sync_to_github
  - save_state
  - verify_infra

variables:
  GITHUB_BRANCH: main
  GITHUB_REPO: github.com/Felix-neko/architecture-future_2_0.git
  TF_ROOT: task_1_terraform_module/terraform
  NODE_IPS_FILE: task_1_terraform_module/.node_ips
  AWS_ACCESS_KEY_ID: ${YC_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${YC_SECRET_ACCESS_KEY}
  AWS_DEFAULT_REGION: ru-central1
  PROXMOX_USER: root@pam
  PROXMOX_PORT: "8006"

smoke_test:
  stage: smoke_test
  image: alpine:latest
  script:
    - echo "Smoke Test"
    - echo "Pipeline $CI_PIPELINE_ID"

terraform_lint:
  stage: terraform_lint
  image:
    name: hashicorp/terraform:1.6
    entrypoint: [""]
  script:
    - echo "Terraform Lint"
    - cd ${TF_ROOT}/vm_module
    - terraform version
    - terraform init -backend=false
    - terraform validate
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"

terraform_apply:
  stage: terraform_apply
  image:
    name: hashicorp/terraform:1.6
    entrypoint: [""]
  before_script:
    - apk add --no-cache bash curl jq openssh-client sshpass aws-cli
    - |
      # Настройка AWS CLI для Yandex S3
      mkdir -p ~/.aws
      echo "[default]" > ~/.aws/credentials
      echo "aws_access_key_id = $YC_ACCESS_KEY_ID" >> ~/.aws/credentials
      echo "aws_secret_access_key = $YC_SECRET_ACCESS_KEY" >> ~/.aws/credentials
      echo "[default]" > ~/.aws/config
      echo "region = ru-central1" >> ~/.aws/config
  script:
    - echo "=== Terraform Apply ==="
    - |
      # Читаем IP адреса из .node_ips файла
      NODE_IPS=$(cat ${NODE_IPS_FILE} | tr '\n' ',' | sed 's/,$//')
      echo "Proxmox nodes: $NODE_IPS"
      
      # Экспортируем переменные для terraform
      export TF_VAR_proxmox_node_ips="[\"$(echo $NODE_IPS | sed 's/,/\",\"/g')\"]"
      export TF_VAR_proxmox_root_password="${PROXMOX_PASSWORD}"
      
      for ENV_DIR in ${TF_ROOT}/environments/dev-*/; do
        if [ -d "$ENV_DIR" ]; then
          ENV_NAME=$(basename "$ENV_DIR")
          echo ""
          echo "=========================================="
          echo "=== Processing $ENV_NAME ==="
          echo "=========================================="
          
          cd "$CI_PROJECT_DIR/$ENV_DIR"
          
          # ШАГ 1: Скачиваем существующий tfstate из S3 (если есть)
          echo "--- Step 1: Download existing state from S3 ---"
          S3_STATE="s3://${YC_S3_BUCKET}/terraform-states/${ENV_NAME}/terraform.tfstate"
          if aws s3 ls "$S3_STATE" --endpoint-url "${YC_S3_ENDPOINT}" 2>/dev/null; then
            echo "Found existing state in S3, downloading..."
            aws s3 cp "$S3_STATE" ./terraform.tfstate --endpoint-url "${YC_S3_ENDPOINT}"
            echo "State downloaded. Resources in state:"
            jq -r '.resources[] | "  - \(.type).\(.name)"' terraform.tfstate 2>/dev/null || echo "  (empty or invalid)"
          else
            echo "No existing state in S3 for $ENV_NAME, starting fresh"
          fi
          
          # ШАГ 2: Terraform init и apply
          echo "--- Step 2: Terraform init ---"
          terraform init
          
          echo "--- Step 3: Terraform plan ---"
          terraform plan -out=tfplan
          
          echo "--- Step 4: Terraform apply ---"
          terraform apply -auto-approve tfplan
          
          # ШАГ 3: Загружаем новый state в S3
          echo "--- Step 5: Upload new state to S3 ---"
          aws s3 cp ./terraform.tfstate "$S3_STATE" --endpoint-url "${YC_S3_ENDPOINT}"
          echo "State uploaded to S3"
          
          echo "--- State summary for $ENV_NAME ---"
          jq -r '.resources[] | "  - \(.type).\(.name)"' terraform.tfstate 2>/dev/null || echo "  (no resources)"
          
          cd "$CI_PROJECT_DIR"
        fi
      done
  artifacts:
    paths:
      - ${TF_ROOT}/environments/dev-1/terraform.tfstate
      - ${TF_ROOT}/environments/dev-2/terraform.tfstate
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"

sync_to_github:
  stage: sync_to_github
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - echo "Sync to GitHub"
    - |
      if [ -z "$GITHUB_TOKEN" ]; then
        echo "GITHUB_TOKEN not set, skipping"
        exit 0
      fi
    - git config --global user.email "gitlab-ci@local"
    - git config --global user.name "GitLab-CI"
    - git remote add github "https://x-access-token:${GITHUB_TOKEN}@${GITHUB_REPO}" || true
    - git push github HEAD:${GITHUB_BRANCH} --force || echo "Push failed"
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"
  allow_failure: true

save_state:
  stage: save_state
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  dependencies:
    - terraform_apply
  script:
    - echo "Save State to S3"
    - |
      if [ -z "$YC_ACCESS_KEY_ID" ] || [ -z "$YC_SECRET_ACCESS_KEY" ]; then
        echo "S3 credentials not set"
        exit 1
      fi
    - mkdir -p ~/.aws
    - echo "[default]" > ~/.aws/credentials
    - echo "aws_access_key_id = $YC_ACCESS_KEY_ID" >> ~/.aws/credentials
    - echo "aws_secret_access_key = $YC_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - echo "[default]" > ~/.aws/config
    - echo "region = ru-central1" >> ~/.aws/config
    - aws s3 ls "s3://${YC_S3_BUCKET}/" --endpoint-url "${YC_S3_ENDPOINT}" || echo "Bucket empty"
    - |
      for ENV_DIR in ${TF_ROOT}/environments/*/; do
        if [ -d "$ENV_DIR" ]; then
          ENV_NAME=$(basename "$ENV_DIR")
          STATE_FILE="${ENV_DIR}terraform.tfstate"
          echo "Processing: $ENV_NAME"
          if [ -f "$STATE_FILE" ]; then
            echo "Uploading $STATE_FILE"
            aws s3 cp "$STATE_FILE" "s3://${YC_S3_BUCKET}/terraform-states/${ENV_NAME}/terraform.tfstate" --endpoint-url "${YC_S3_ENDPOINT}"
          else
            echo "No state file for $ENV_NAME"
          fi
        fi
      done
    - |
      echo '{"pipeline":"'$CI_PIPELINE_ID'","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > /tmp/meta.json
      aws s3 cp /tmp/meta.json "s3://${YC_S3_BUCKET}/terraform-states/_pipeline_${CI_PIPELINE_ID}.json" --endpoint-url "${YC_S3_ENDPOINT}"
    - aws s3 ls "s3://${YC_S3_BUCKET}/terraform-states/" --recursive --endpoint-url "${YC_S3_ENDPOINT}" || true
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"

verify_infra:
  stage: verify_infra
  image: alpine:latest
  dependencies:
    - terraform_apply
  before_script:
    - apk add --no-cache curl jq aws-cli
  script:
    - chmod +x task_2_stage_saved_in_s3/scripts/verify_state.sh
    - sh task_2_stage_saved_in_s3/scripts/verify_state.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "terraform"
